AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Nice Api for user handling (without API Gateway configuration).

Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FunctionCreateUser:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPost
      SyncedEventProperties:
        RootPost:
          - Path
          - Method
    Properties:
      FunctionName: niceapi-users-create # Nombre personalizado de la función
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: Users
      PackageType: Zip
      Handler: NiceApiUsers::NiceAppApi.Users.Functions_CreateUser_Generated::CreateUser

  FunctionUpdateUser:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootPut
      SyncedEventProperties:
        RootPut:
          - Path
          - Method
    Properties:
      FunctionName: niceapi-users-update # Nombre personalizado de la función
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: Users
      PackageType: Zip
      Handler: NiceApiUsers::NiceAppApi.Users.Functions_UpdateUser_Generated::UpdateUser

  FunctionGetUser:
    Type: AWS::Serverless::Function
    Metadata:
      Tool: Amazon.Lambda.Annotations
      SyncedEvents:
        - RootGet
      SyncedEventProperties:
        RootGet:
          - Path
          - Method
    Properties:
      FunctionName: niceapi-users-get # Nombre personalizado de la función
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: Users
      PackageType: Zip
      Handler: NiceApiUsers::NiceAppApi.Users.Functions_GetUser_Generated::GetUser
